prefix=${CMAKE_INSTALL_PREFIX}
exec_prefix=${CMAKE_INSTALL_PREFIX}/bin
libdir=${LIB_INSTALL_DIR}
includedir=${INCLUDE_INSTALL_DIR}/KF5Attica

Name: lib${ATTICA_LIB_SONAME}
Description: Qt library to access Open Collaboration Services
#Requires:
Version: ${CMAKE_LIBATTICA_VERSION_MAJOR}.${CMAKE_LIBATTICA_VERSION_MINOR}.${CMAKE_LIBATTICA_VERSION_PATCH}
Libs: -L${LIB_INSTALL_DIR} -l${ATTICA_LIB_SONAME}
Cflags: -I${INCLUDE_INSTALL_DIR}/KF5Attica
